name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ">=6.0.0-alpha <8.0.0"
  angular_forms: ">=2.1.0 <5.0.0"
  angular_router: ">=2.0.0-alpha <4.0.0"
  http: ">=0.12.0 <0.14.0"
  stream_transform: ">=0.0.19 <3.0.0"

dev_dependencies:
  angular_test: ">=2.3.1 <5.0.0"
  build_runner: ">=1.5.1 <3.0.0"
  build_test: ">=0.10.8 <3.0.0"
  build_web_compilers: ">=2.1.0 <4.0.0"
  test: ^1.6.4
